### ISSUE TITLE
[NET6] Error with latest version

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno.xamlmerge.task#131]
## Current behavior

Getting the following error on the latest version.

```
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018: The "BatchMergeXaml_f76645703193d279913d46c9181e0642bc79c095" task failed unexpectedly.
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018: System.ArgumentOutOfRangeException: Insertion index was out of range. Must be non-negative and less than or equal to size.
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018: Parameter name: index
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at System.Collections.ArrayList.Insert(Int32 index, Object value)
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at System.Xml.XmlNamedNodeMap.InsertNodeAt(Int32 i, XmlNode node)
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at System.Xml.XmlAttributeCollection.InsertNodeAt(Int32 i, XmlNode node)
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at System.Xml.XmlAttributeCollection.InsertAfter(XmlAttribute newNode, XmlAttribute refNode)
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at Uno.UI.Tasks.BatchMerge.BatchMergeXaml_f76645703193d279913d46c9181e0642bc79c095.BatchMerger.Merge(CustomTask owner, String mergedXamlFile, String projectFullPath, ITaskItem[] pageItems) in /_/src/Uno.XamlMerge.Task/BatchMergeXaml.cs:line 257
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at Uno.UI.Tasks.BatchMerge.BatchMergeXaml_f76645703193d279913d46c9181e0642bc79c095.Execute() in /_/src/Uno.XamlMerge.Task/BatchMergeXaml.cs:line 49
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\tommy-lee.pigeon\.nuget\packages\uno.xamlmerge.task\1.26.0-dev.40\build\Uno.XamlMerge.Task.targets(15,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [x] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Soap-141** [comment]
As requested. I can probably try to create a sample application but it will have to wait, busy at the moment.

**Comment by Youssef1313** [comment]
A repro would be very helpful indeed.

**Comment by Soap-141** [comment]
Just found out how to reproduce it, delete generated file change version and try to build again.

**Comment by Soap-141** [comment]
Restarting the computer on version changes works.

**Comment by Youssef1313** [comment]
@Soap-141 So this is no longer an issue?

**Comment by Soap-141** [comment]
@Youssef1313 Nop
